### ISSUE TITLE
[FR] add the ability to select a nickname in panel "Quick connect" like in UrT Connector.

### ISSUE THREAD

**Issue by KronoZed** [pztrn/urtrator#4]
Feature request for add the ability to select a nickname in panel "Quick connect" like in UrT Connector.

![UrT Connector](http://i.imgur.com/YW2OT3h.png)

**Comment by pztrn** [comment]
This can be achieved with profiles, so no separate field for this.

**Comment by KronoZed** [comment]
Profiles do not solve it for the games with frequent change nickname

![UrTConnector](http://i.imgur.com/YW2OT3h.png)

**Comment by pztrn** [comment]
Shitty idea, but okay.

**Comment by pztrn** [comment]
Done.
